// Auto-generated from TestClassWithStub.cs

import TestClass2 from './TestClass2';
import TestClassInFolder from './SubFolder1/SubFolder2/TestClassInFolder';
import GenericClass1 from './GenericClass1';
import TestEnum from './TestEnum';
import GenericClass2 from './GenericClass2';
import TestEnumInFolder from './Enums/TestEnumInFolder';

interface TestClassWithStub {
  intProperty: number;
  nullableIntProperty: number | null;
  longProperty: number;
  nullableLongProperty: number | null;
  floatProperty: number;
  nullableFloatProperty: number | null;
  doubleProperty: number;
  nullableDoubleProperty: number | null;
  decimalProperty: number;
  nullableDecimalProperty: number | null;
  boolProperty: boolean;
  nullableBoolProperty: boolean | null;
  charProperty: string;
  nullableCharProperty: string | null;
  byteProperty: number;
  nullableByteProperty: number | null;
  sByteProperty: number;
  nullableSByteProperty: number | null;
  shortProperty: number;
  nullableShortProperty: number | null;
  uShortProperty: number;
  nullableUShortProperty: number | null;
  uIntProperty: number;
  nullableUIntProperty: number | null;
  uLongProperty: number;
  nullableULongProperty: number | null;
  stringProperty: string;
  nullableStringProperty: string | null;
  guidProperty: string;
  nullableGuidProperty: string | null;
  dateTimeProperty: string;
  nullableDateTimeProperty: string | null;
  dateTimeOffsetProperty: string;
  nullableDateTimeOffsetProperty: string | null;
  dateOnlyProperty: string;
  nullableDateOnlyProperty: string | null;
  timeOnlyProperty: string;
  nullableTimeOnlyProperty: string | null;
  thisClass: TestClass;
  class2: TestClass2;
  classInFolder: TestClassInFolder;
  genericArray: GenericClass1<number[]>;
  nullableGeneric: GenericClass1<number | null>;
  genericClass1: GenericClass1<TestClass>;
  genericClass2: GenericClass2<TestClass, TestEnum>;
  enum: TestEnum;
  nullableEnum: TestEnum | null;
  enumInFolder: TestEnumInFolder;
  formFile: File;
  iFormFile: File;
  json: unknown;
  intEnumerable: number[];
  tSNullableIntEnumerable: number[] | null;
  intCollection: number[];
  intIList: number[];
  intList: number[];
  int2JaggedList: number[][];
  int3JaggedList: number[][][];
  intArray: number[];
  int2JaggedArray: number[][];
  int3JaggedArray: number[][][];
  intDictionary: { [key: string]: number };
  intIDictionary: { [key: string]: number };
  intArrayIDictionary: { [key: string]: number[] };
  stringListIDictionary: { [key: string]: string[] };
  intHashSet: number[];
  intISet: number[];
  intQueue: number[];
  intStack: number[];
  intLinkedList: number[];
  intSortedSet: number[];
  intSortedList: { [key: string]: number };
  intSortedDictionary: { [key: string]: number };
  intReadOnlyCollection: number[];
  intReadOnlyList: number[];
  intReadOnlyDictionary: number[];
  intCollection2: number[];
  intConcurrentBag: number[];
  formFileCollection: File[];
  iFormFileCollection: File[];
  nullableIntEnumerable: (number | null)[];
  tSNullableNullableIntEnumerable: (number | null)[] | null;
  nullableIntCollection: (number | null)[];
  nullableIntIList: (number | null)[];
  nullableIntList: (number | null)[];
  nullableIntArray: (number | null)[];
  nullableIntDictionary: { [key: string]: (number | null) };
  nullableIntIDictionary: { [key: string]: (number | null) };
  nullableIntHashSet: (number | null)[];
  nullableIntISet: (number | null)[];
  nullableIntQueue: (number | null)[];
  nullableIntStack: (number | null)[];
  nullableIntLinkedList: (number | null)[];
  nullableIntSortedSet: (number | null)[];
  nullableIntSortedList: { [key: string]: (number | null) };
  nullableIntSortedDictionary: { [key: string]: (number | null) };
  nullableIntReadOnlyCollection: (number | null)[];
  nullableIntReadOnlyList: (number | null)[];
  nullableIntReadOnlyDictionary: (number | null)[];
  nullableIntCollection2: (number | null)[];
  nullableIntConcurrentBag: (number | null)[];
}

export default TestClassWithStub;

export class TestClassWithStubStub implements TestClassWithStub {
  intProperty: number = 0;
  nullableIntProperty: number | null = null;
  longProperty: number = 0;
  nullableLongProperty: number | null = null;
  floatProperty: number = 0;
  nullableFloatProperty: number | null = null;
  doubleProperty: number = 0;
  nullableDoubleProperty: number | null = null;
  decimalProperty: number = 0;
  nullableDecimalProperty: number | null = null;
  boolProperty: boolean = false;
  nullableBoolProperty: boolean | null = null;
  charProperty: string = '';
  nullableCharProperty: string | null = null;
  byteProperty: number = 0;
  nullableByteProperty: number | null = null;
  sByteProperty: number = 0;
  nullableSByteProperty: number | null = null;
  shortProperty: number = 0;
  nullableShortProperty: number | null = null;
  uShortProperty: number = 0;
  nullableUShortProperty: number | null = null;
  uIntProperty: number = 0;
  nullableUIntProperty: number | null = null;
  uLongProperty: number = 0;
  nullableULongProperty: number | null = null;
  stringProperty: string = '';
  nullableStringProperty: string | null = null;
  guidProperty: string = '';
  nullableGuidProperty: string | null = null;
  dateTimeProperty: string = '';
  nullableDateTimeProperty: string | null = null;
  dateTimeOffsetProperty: string = '';
  nullableDateTimeOffsetProperty: string | null = null;
  dateOnlyProperty: string = '';
  nullableDateOnlyProperty: string | null = null;
  timeOnlyProperty: string = '';
  nullableTimeOnlyProperty: string | null = null;
  thisClass: TestClass = {} as TestClass;
  class2: TestClass2 = {} as TestClass2;
  classInFolder: TestClassInFolder = {} as TestClassInFolder;
  genericArray: GenericClass1<number[]> = {} as GenericClass1<number[]>;
  nullableGeneric: GenericClass1<number | null> = {} as GenericClass1<number | null>;
  genericClass1: GenericClass1<TestClass> = {} as GenericClass1<TestClass>;
  genericClass2: GenericClass2<TestClass, TestEnum> = {} as GenericClass2<TestClass, TestEnum>;
  enum: TestEnum = TestEnum.Value1;
  nullableEnum: TestEnum | null = null;
  enumInFolder: TestEnumInFolder = TestEnumInFolder.Value1;
  formFile: File = {} as File;
  iFormFile: File = {} as File;
  json: unknown = {} as unknown;
  intEnumerable: number[] = [];
  tSNullableIntEnumerable: number[] | null = null;
  intCollection: number[] = [];
  intIList: number[] = [];
  intList: number[] = [];
  int2JaggedList: number[][] = [];
  int3JaggedList: number[][][] = [];
  intArray: number[] = [];
  int2JaggedArray: number[][] = [];
  int3JaggedArray: number[][][] = [];
  intDictionary: { [key: string]: number } = {};
  intIDictionary: { [key: string]: number } = {};
  intArrayIDictionary: { [key: string]: number[] } = {};
  stringListIDictionary: { [key: string]: string[] } = {};
  intHashSet: number[] = [];
  intISet: number[] = [];
  intQueue: number[] = [];
  intStack: number[] = [];
  intLinkedList: number[] = [];
  intSortedSet: number[] = [];
  intSortedList: { [key: string]: number } = {};
  intSortedDictionary: { [key: string]: number } = {};
  intReadOnlyCollection: number[] = [];
  intReadOnlyList: number[] = [];
  intReadOnlyDictionary: number[] = [];
  intCollection2: number[] = [];
  intConcurrentBag: number[] = [];
  formFileCollection: File[] = [];
  iFormFileCollection: File[] = [];
  nullableIntEnumerable: (number | null)[] = [];
  tSNullableNullableIntEnumerable: (number | null)[] | null = null;
  nullableIntCollection: (number | null)[] = [];
  nullableIntIList: (number | null)[] = [];
  nullableIntList: (number | null)[] = [];
  nullableIntArray: (number | null)[] = [];
  nullableIntDictionary: { [key: string]: (number | null) } = {};
  nullableIntIDictionary: { [key: string]: (number | null) } = {};
  nullableIntHashSet: (number | null)[] = [];
  nullableIntISet: (number | null)[] = [];
  nullableIntQueue: (number | null)[] = [];
  nullableIntStack: (number | null)[] = [];
  nullableIntLinkedList: (number | null)[] = [];
  nullableIntSortedSet: (number | null)[] = [];
  nullableIntSortedList: { [key: string]: (number | null) } = {};
  nullableIntSortedDictionary: { [key: string]: (number | null) } = {};
  nullableIntReadOnlyCollection: (number | null)[] = [];
  nullableIntReadOnlyList: (number | null)[] = [];
  nullableIntReadOnlyDictionary: (number | null)[] = [];
  nullableIntCollection2: (number | null)[] = [];
  nullableIntConcurrentBag: (number | null)[] = [];

  constructor(data?: Partial<TestClassWithStub>) {
    if (data) {
      Object.assign(this, data);
    }
  }
}
