// Auto-generated from TestClass.cs

import TestClass2 from './TestClass2';
import TestClassInFolder from './SubFolder1/SubFolder2/TestClassInFolder';
import GenericClass1 from './GenericClass1';
import TestEnum from './TestEnum';
import GenericClass2 from './GenericClass2';
import TestEnumInFolder from './Enums/TestEnumInFolder';

interface TestClass {
  IntProperty: number;
  NullableIntProperty: number | null;
  LongProperty: number;
  NullableLongProperty: number | null;
  FloatProperty: number;
  NullableFloatProperty: number | null;
  DoubleProperty: number;
  NullableDoubleProperty: number | null;
  DecimalProperty: number;
  NullableDecimalProperty: number | null;
  BoolProperty: boolean;
  NullableBoolProperty: boolean | null;
  CharProperty: string;
  NullableCharProperty: string | null;
  ByteProperty: number;
  NullableByteProperty: number | null;
  SByteProperty: number;
  NullableSByteProperty: number | null;
  ShortProperty: number;
  NullableShortProperty: number | null;
  UShortProperty: number;
  NullableUShortProperty: number | null;
  UIntProperty: number;
  NullableUIntProperty: number | null;
  ULongProperty: number;
  NullableULongProperty: number | null;
  UtringProperty: string;
  NullableStringProperty: string | null;
  UuidProperty: string;
  NullableGuidProperty: string | null;
  DateTimeProperty: string;
  NullableDateTimeProperty: string | null;
  DateTimeOffsetProperty: string;
  NullableDateTimeOffsetProperty: string | null;
  DateOnlyProperty: string;
  NullableDateOnlyProperty: string | null;
  TimeOnlyProperty: string;
  NullableTimeOnlyProperty: string | null;
  ThisClass: TestClass;
  Class2: TestClass2;
  ClassInFolder: TestClassInFolder;
  GenericArray: GenericClass1<number[]>;
  NullableGeneric: GenericClass1<number | null>;
  GenericClass1: GenericClass1<TestClass>;
  GenericClass2: GenericClass2<TestClass, TestEnum>;
  Enum: TestEnum;
  NullableEnum: TestEnum | null;
  EnumInFolder: TestEnumInFolder;
  FormFile: File;
  IFormFile: File;
  Json: unknown;
  IntEnumerable: number[];
  TSNullableIntEnumerable: number[] | null;
  IntCollection: number[];
  IntIList: number[];
  IntList: number[];
  Int2JaggedList: number[][];
  Int3JaggedList: number[][][];
  IntArray: number[];
  Int2JaggedArray: number[][];
  Int3JaggedArray: number[][][];
  IntDictionary: { [key: string]: number };
  IntIDictionary: { [key: string]: number };
  IntArrayIDictionary: { [key: string]: number[] };
  StringListIDictionary: { [key: string]: string[] };
  IntHashSet: number[];
  IntISet: number[];
  IntQueue: number[];
  IntStack: number[];
  IntLinkedList: number[];
  IntSortedSet: number[];
  IntSortedList: { [key: string]: number };
  IntSortedDictionary: { [key: string]: number };
  IntReadOnlyCollection: number[];
  IntReadOnlyList: number[];
  IntReadOnlyDictionary: number[];
  IntCollection2: number[];
  IntConcurrentBag: number[];
  FormFileCollection: File[];
  IFormFileCollection: File[];
  NullableIntEnumerable: (number | null)[];
  TSNullableNullableIntEnumerable: (number | null)[] | null;
  NullableIntCollection: (number | null)[];
  NullableIntIList: (number | null)[];
  NullableIntList: (number | null)[];
  NullableIntArray: (number | null)[];
  NullableIntDictionary: { [key: string]: (number | null) };
  NullableIntIDictionary: { [key: string]: (number | null) };
  NullableIntHashSet: (number | null)[];
  NullableIntISet: (number | null)[];
  NullableIntQueue: (number | null)[];
  NullableIntStack: (number | null)[];
  NullableIntLinkedList: (number | null)[];
  NullableIntSortedSet: (number | null)[];
  NullableIntSortedList: { [key: string]: (number | null) };
  NullableIntSortedDictionary: { [key: string]: (number | null) };
  NullableIntReadOnlyCollection: (number | null)[];
  NullableIntReadOnlyList: (number | null)[];
  NullableIntReadOnlyDictionary: (number | null)[];
  NullableIntCollection2: (number | null)[];
  NullableIntConcurrentBag: (number | null)[];
}

export default TestClass;
